spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: library-management-system
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  packages-to-scan: dev.zbib.librarymanagement


server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /api

jwt:
  secret: 2b3cb49cc5b8861281a08b53a1f7676942aad43c5cdf35b6b1c80aa608a54bae10f8e3a98d10744b6e9fa69bee3e1f5311fcff3c8706ef21ab631b852d42e277
  expiration: 172800

logging:
  pattern:
    console: "[%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}] [%p] [correlation-id=%X{correlationId}] %m%n"
  level:
    root: WARN
    org.hibernate: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.springframework.web: WARN
    dev.zbib.librarymanagement: INFO
    com.zaxxer.hikari: WARN